/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocumentUploadQueue: typeof import('./components/document/DocumentUploadQueue.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    PageThumbnailStrip: typeof import('./components/document/PageThumbnailStrip.vue')['default']
    PrivateImage: typeof import('./components/document/PrivateImage.vue')['default']
    RegionOverlay: typeof import('./components/document/RegionOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentPageOrganizer: typeof import('./components/document/StudentPageOrganizer.vue')['default']
    UploadProgressItem: typeof import('./components/document/UploadProgressItem.vue')['default']
  }
}
